### ISSUE TITLE
Adding options doesnot not seems to be working

### ISSUE THREAD

**Issue by amitmoondra** [wnabil/ngx-export-as#18]
when adding options it doesnot work (take any effect), can you provide me with a working example of adding option and also how to add header with image and footer with page number.

**Comment by wnabil** [comment]
please check the readme file, here is an example how to set the custom options and do not forget to check each library for its special options
https://github.com/wnabil/ngx-export-as#configuration

**Comment by rocaramon** [comment]
Hi i have the same problem when trying to add configuration for PDF , i was trying to add the  current configuration and none if the two worked

`  config: ExportAsConfig = {
    type: 'pdf',
    elementId: 'statementTable',
    options: {   margin:       1,
  filename:     'myfile.pdf',
  image:        { type: 'jpeg', quality: 0.98 },
  html2canvas:  { scale: 2 },
  jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
    }
  }`

`  config: ExportAsConfig = {
    type: 'pdf',
    elementId: 'statementTable',
    options: { 
  jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
    }
  }`

**Comment by wnabil** [comment]
Tested and working fine as expected, please check the demo code i updated it with an example to pdf orientation.
@rocaramon it doesn't work because you did not change anything, this is the default options!
`options: { jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' } }`
![image](https://user-images.githubusercontent.com/23165327/59256072-76734f80-8c33-11e9-9d25-4a58c74022c9.png)
