### ISSUE TITLE
Custom Header

### ISSUE THREAD

**Issue by mdsunely** [wnabil/ngx-export-as#24]
Hello,

Is there any way that I can't add some extra images and text in header while exporting PDF?

Thanks & Regards
Mohammed Sunely

**Comment by wnabil** [comment]
I think it will work if you added the data at the top of the HTML and hided them with CSS or [hidden] directive, if this did not work then you can make it visible during the exporting and re-hiding it when its done
something like this:
```javascript
this.displaySignature = true;
this.exportAsService.save(this.exportAsConfig, 'My File Name').subscribe(() => {
      // save started
      this.displaySignature = false;
});
```

```html
<div id="sig" [hidden]="!displaySignature">
</div>
```
 OR more secure with ngIf

```html
<div id="sig" *ngIf="displaySignature">
</div>
```

I published a new version `1.2.6` in order to support the subscriptions in `save` method
