### ISSUE TITLE
Export as Excel or PDF or etc, don't have a headers

### ISSUE THREAD

**Issue by shyam9396** [wnabil/ngx-export-as#28]
we are missing here Headers setting, every page has to have a Header and we don't have much control on this plugin, that is big drawback, when we have full control on customization that will give flexibility.

**Comment by wnabil** [comment]
What do you mean by the headers setting ?

**Comment by shyam9396** [comment]
EX:-
Header : Title, Description, Value
These above titles has to print in every page of Header section and Styling control

**Comment by wnabil** [comment]
`
Typescript angular module to export Table/HTML to popular file formats
`
As simple as it is, This package exports only the HTML Elements to a file format and per format file customization are not supported and not actually the goal of this project, Pull request is welcome for sure if you were able to manage it.

However you can set some styles using the options but it will not do what you want, since the header and footer and other things like this are special to specific file types like PDF then we have nothing to do with here.
The best choice for you is uninstall the package and install html2pdf or jspdf and use the functions inside it to manage your requirements.
