### ISSUE TITLE
Blank PDF in Ionic 4

### ISSUE THREAD

**Issue by ravimallya** [wnabil/ngx-export-as#47]
Hello,

I've a ion-row element which has two columns, and inside of those, I have two tables. I've wrapped entire ion-row with a div and I'm trying to export to PDF. I'm getting a blank pdf with header/footer callback - which works fine.

Does this plugin will work with Ionic 4?

**Comment by ravimallya** [comment]
If I wrap the tables with plain div without using ion-grid layout, export works fine. Is there anyway to get it worked with ionic grid or such ionic components?

**Comment by wnabil** [comment]
Yes it works, seems like a styling issue with html2pdf or html2canvas because ionic use flex layout now and i do not think the used libraries supports them, however the best thing to do is to render the table twice, one using the ionic structure and one without and completely hidden "just for the export".
to make the code even better you can create a shared component to handle the hidden one so you do not repeat the code every time.

for the second issue you mentioned i will keep an eye on it and directly update the library when its fixed, thanks for the details

**Comment by ravimallya** [comment]
Thank you. @wnabil . I've updated the other one with my code to export to PDF.
