### ISSUE TITLE
How to export Exce File with styles 

### ISSUE THREAD

**Issue by wushunqing** [wnabil/ngx-export-as#6]
How to export Exce File with styles ?
Now,I'm use this Plug，but not with any styles .
Please Help me.

**Comment by wnabil** [comment]
Hi, sorry for the delay

In order to do that check the custom options for the library you are using, in your case its [SheetJS js-xlsx](https://github.com/SheetJS/js-xlsx)

you can pass this options in the options property inside your exportasconfig object
please refer to readme.md file at this section for this details: https://github.com/wnabil/ngx-export-as#configuration
