### ISSUE TITLE
Cannot export Option Value

### ISSUE THREAD

**Issue by dianesabra** [wnabil/ngx-export-as#92]
![Export Problem](https://user-images.githubusercontent.com/43650106/114947959-ada87e00-9e13-11eb-8a97-c61772002b3b.png)

Hello!
First of all, thank you for building a package that was easy to implement!

I ran into an issue when I was exporting a list of inventory and found that an input field wouldn't export with the value, it exports with the list of values.

For example, the Status fields has four options: Make Ready, Available, Sold, and Repair. For the first vehicle, the status is Make Ready. When it exports, the Excel shows the four options rather than the correct status.

I've attached a picture for convenience.

Thanks in advance!

- D

**Comment by wnabil** [comment]
Replace the list with a simple text of the actual value then return it after the export "that's why we switched to use rxjs in save and get methods"
html2pdf fetches the exact content from the Dom element and displays it with no javascript logic support
also you can check html2pdf library in case if they have a workaround using the options
