### ISSUE TITLE
 Module not found: Error: Can't resolve 'util' in 'E:\potatoLogics\name\node_modules\xmlbuilder2\lib'

### ISSUE THREAD

**Issue by tahir-jamil** [wnabil/ngx-export-as#99]
Hi i have installed ngx-export-as for the very first time and i am getting following error please help me fixing this
![image](https://user-images.githubusercontent.com/40952630/137087594-37b9c699-401e-41cd-9951-cef17910b07c.png)

**Comment by JoeWorker** [comment]
npm install util

takes away the error

**Comment by chernodub** [comment]
## In case you're using Node 16 and Angular 13+

I figured out a way to resolve this **without installing any polyfills** by doing the following:
* fall back to `1.12.0` by running `npm i ngx-export-as@1.12.0`
* add an `overrides` section to `package.json` (instead of `~13.3.10` you could use your current Angular version)
	```json
	    "overrides": {
	      "ngx-export-as": {
	        "@angular/core": "~13.3.10",
	        "@angular/common": "~13.3.10"
	      }
	    }
	```
